insert into Tags (Id, Name)
values
(newid(), 'home'),
(newid(), 'belarus-major-league'),
(newid(), 'belarus-cup'),
(newid(), 'belarus-1-league'),
(newid(), 'belarus-2-league'),
(newid(), 'belarus-regions'),
(newid(), 'belarus-ours-abroad'),
(newid(), 'uefa-champions-league'),
(newid(), 'uefa-europa-league'),
(newid(), 'fifa-clubs-world-cup'),
(newid(), 'uefa-regions-league'),
(newid(), 'uefa-euro-2021'),
(newid(), 'uefa-nations-league'),
(newid(), 'fifa-world-cup-2022'),
(newid(), 'national-out-of-europe'),
(newid(), 'england'),
(newid(), 'spain'),
(newid(), 'germany'),
(newid(), 'italy'),
(newid(), 'france'),
(newid(), 'russia'),
(newid(), 'ukraine'),
(newid(), 'spain'),
(newid(), 'other')
